package jsanzo.movies.domain.model

data class DomainMovieDetails(
    val adult: Boolean,
    val backdropPath: String?,
    val belongsToCollection: DomainMovieCollection?,
    val budget: Int,
    val genres: List<DomainMovieGenre>,
    val homepage: String?,
    val id: Int,
    val imdbId: String?,
    val originCountry: List<String>,
    val originalLanguage: String,
    val originalTitle: String,
    val overview: String?,
    val popularity: Double,
    val posterPath: String?,
    val productionCompanies: List<DomainMovieProductionCompany>,
    val productionCountries: List<DomainMovieProductionCountry>,
    val releaseDate: String,
    val revenue: Long,
    val runtime: Int?,
    val spokenLanguages: List<DomainMovieSpokenLanguage>,
    val status: String,
    val tagline: String?,
    val title: String,
    val video: Boolean,
    val voteAverage: Double,
    val voteCount: Int,
)
